### ISSUE TITLE
osc communication help

### ISSUE THREAD

**Issue by warpmick** [Deep-Symmetry/open-beat-control#8]
hello first, thanks to all team members for the job you ve done on this project. 

i try raspberry version seem work nice, to sync an mpclive (ableton link compatible) to xdj,  if set -r -d 4 -B -a args
well got mpc tempo master but if an xdj decide to take master tempo never manage to give it back to mpclive again

i try to call osc serveur /master appoint nbplayer function 
tryed many way c# c++ phyton nothing seem too work 
just manage to produce a parsing error logged  in terminal on sending a random upd packet to the server. 

is they a way to have log file on osc server activity 
incoming call, state... for investigate ? 

i dont know well the protocol maybe i miss something  , should someone help me to get on the way ? 

thanks, 
mickael

**Comment by brunchboy** [comment]
Hi, thanks for trying out Open Beat Control! If you are looking for help with the OSC protocol, I would look for a library that implements it in your target language, and use that instead of trying to make packets yourself. Then ask that community for support if you need it. This project is designed for people who already have strong reasons to be using OSC as a control protocol. If you just want to experiment with interacting with Pioneer gear, I’d recommend using Beat Link Trigger and Clojure, or the Beat Link library directly and Java.

If you would like to log more things, then fork the project and add more log lines at appropriate places. `(timbre/info "some description" some-value)`.

If you would like conversations with other people who are using these projects and who might be able to help you, the place is the [Deep Symmetry Zulip](https://deep-symmetry.zulipchat.com/#narrow/stream/275322-beat-link-trigger).
